{% set name = "erdantic" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/erdantic-{{ version }}.tar.gz
  sha256: e35cc1babb37b8dc62fc220ce61a167afaebd11e391c6bd53882918a3b01644b

build:
  number: 1
  noarch: python
  entry_points:
    - erdantic=erdantic.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - pydantic >=2
    - pydantic-core
    - pygraphviz
    - python >={{ python_min }}
    - sortedcontainers-pydantic
    - typenames >=1.3
    - typer
    - typing-extensions

test:
  imports:
    - erdantic
    - erdantic.examples
  commands:
    - pip check
    - erdantic --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drivendataorg/erdantic
  summary: Entity relationship diagrams for Python data model classes like Pydantic.
  license: MIT
  license_file: LICENSE
  doc_url: https://erdantic.drivendata.org/
  dev_url: https://github.com/drivendataorg/erdantic

extra:
  recipe-maintainers:
    - jayqi
