{% set name = "erdantic" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erdantic-{{ version }}.tar.gz
  sha256: 274dcd7b8b4129c3460a5ab808606b20090466a1d49f67777e3e74b0c89ff429

build:
  number: 0
  noarch: python
  entry_points:
    - erdantic=erdantic.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - pydantic >=2
    - pydantic-core
    - pygraphviz
    - python >=3.8
    - sortedcontainers-pydantic
    - typenames
    - typer
    - typing-extensions

test:
  imports:
    - erdantic
    - erdantic.examples
  commands:
    - pip check
    - erdantic --help
  requires:
    - pip

about:
  home: https://github.com/drivendataorg/erdantic
  summary: Entity relationship diagrams for Python data model classes like Pydantic.
  license: MIT
  license_file: LICENSE
  doc_url: https://erdantic.drivendata.org/
  dev_url: https://github.com/drivendataorg/erdantic

extra:
  recipe-maintainers:
    - jayqi
