{% set name = "erdantic" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erdantic-{{ version }}.tar.gz
  sha256: 475389523b37b1ac06a96837d782a41b889fb27d099a1576183f1721a6a38e23

build:
  number: 0
  noarch: python
  entry_points:
    - erdantic=erdantic.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - importlib-metadata
    - pydantic
    - pygraphviz
    - python >=3.6
    - typer
    - typing-extensions

test:
  imports:
    - erdantic
    - erdantic.examples
  commands:
    - pip check
    - erdantic --help
  requires:
    - pip

about:
  home: https://github.com/drivendataorg/erdantic
  summary: Entity relationship diagrams for Python data model classes like Pydantic.
  license: MIT
  license_file: LICENSE
  doc_url: https://erdantic.drivendata.org/
  dev_url: https://github.com/drivendataorg/erdantic

extra:
  recipe-maintainers:
    - jayqi
